# Generated by Django 4.1.2 on 2023-06-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_user_paul_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
