# Generated by Django 4.1.2 on 2023-06-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateuser',
            name='available_balance',
            field=models.CharField(default='0.00', max_length=7),
        ),
    ]
