# Generated by Django 4.1.2 on 2023-06-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_updateuser_available_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateuser',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
