# Generated by Django 4.1.2 on 2023-06-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_updateuser_available_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateuser',
            name='available_balance',
            field=models.CharField(max_length=100),
        ),
    ]
