# Generated by Django 4.1.2 on 2023-06-15 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('passport_1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('total_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('total_withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('transaction_pin', models.IntegerField(default=0)),
                ('confirm_transaction_pin', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profile Update',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='', max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('receiver_name', models.CharField(default='', max_length=100)),
                ('receiver_bank', models.CharField(default='', max_length=100)),
                ('transaction_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='stock_debits', max_length=10)),
                ('amount', models.IntegerField()),
                ('transaction_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
