# Generated by Django 4.1.2 on 2023-06-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateuser',
            name='passport_1',
        ),
    ]
