# Generated by Django 4.1.2 on 2023-06-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_updateuser_confirm_transaction_pin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='account_number',
            new_name='wallet_address',
        ),
        migrations.RemoveField(
            model_name='history',
            name='description',
        ),
        migrations.RemoveField(
            model_name='history',
            name='receiver_bank',
        ),
        migrations.RemoveField(
            model_name='history',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='sender_name',
        ),
    ]
