# Generated by Django 4.1.2 on 2023-06-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_commodity_crypto_withdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('return_on_investment', models.DecimalField(decimal_places=2, max_digits=50)),
                ('referal_bonus', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
            options={
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.DeleteModel(
            name='Commodity',
        ),
    ]
