# Generated by Django 4.1.2 on 2023-06-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_crypto_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
