# Generated by Django 4.1.2 on 2023-06-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_remove_updateuser_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='transaction_reference',
        ),
        migrations.RemoveField(
            model_name='history',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='history',
            name='plan',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Regular', max_length=10),
        ),
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10),
        ),
    ]
