# Generated by Django 3.2.19 on 2024-05-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_history_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateuser',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('€', 'EUR'), ('£', 'GBP')], default='$', max_length=10),
        ),
    ]
