# Generated by Django 4.1.2 on 2023-06-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_history_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
