# Generated by Django 4.1.2 on 2023-06-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_history_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='sender_name',
        ),
    ]
