# Generated by Django 3.2.19 on 2024-06-10 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_history_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsuccessful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.uuid5, max_length=10)),
            ],
        ),
    ]
