# Generated by Django 3.2.19 on 2024-06-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_unsuccessful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsuccessful',
            name='code',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
