# Generated by Django 3.2.19 on 2024-06-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_unsuccessful_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unsuccessful',
        ),
    ]
